{
  try {
    invoke(this,"fail","hello");
  }
 catch (  AssertionFailedError e) {
  }
}
