{
  try {
    new ObjectRange(null,createValue(5));
    fail("null 'from' accepted");
  }
 catch (  IllegalArgumentException e) {
    assertTrue("expected exception thrown",true);
  }
}
