{
  try {
    range.set(0,AT);
    fail("got set value 0");
  }
 catch (  UnsupportedOperationException e) {
    assertTrue("expected exception thrown",true);
  }
}
