{
  try {
    range.get(0);
    fail("got value from empty range");
  }
 catch (  IndexOutOfBoundsException e) {
    assertTrue("expected exception thrown",true);
  }
}
