{
  try {
    Object value=invoke(this,"unknownMethod","abc");
    fail("Should have thrown an exception");
  }
 catch (  InvokerException e) {
  }
}
