{
  boolean failed=false;
  try {
    code.call();
  }
 catch (  Exception e) {
    if (clazz.isInstance(e)) {
      failed=true;
      System.out.println("Worked: caught expected exception: " + e);
    }
    assertTrue("Closure " + code + " should have failed with an exception of type "+ clazz.getName()+ ", instead got Exception "+ e,failed);
    return;
  }
  assertTrue("Closure " + code + " should have failed with an exception of type "+ clazz.getName(),failed);
}
