{
  boolean failed=false;
  try {
    code.call();
  }
 catch (  Exception e) {
    failed=true;
  }
  assertTrue("Closure " + code + " should have failed",failed);
}
