{
  boolean failed=false;
  try {
    code.call();
  }
 catch (  Exception e) {
    failed=true;
    System.out.println("Worked: caught expected exception: " + e);
  }
  assertTrue("Closure " + code + " should have failed",failed);
}
